name: 'Action 1 - Push Release to Public'
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  copy-release:
    runs-on: 'ubuntu-latest'
    if: github.repository == 'davidhardy5-nhs/test-private'
    steps:
      - name: Checkout private
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.EXTERNAL_REPO_TOKEN }}
          path: private

      - name: Checkout public
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.EXTERNAL_REPO_TOKEN }}
          repository: davidhardy5-nhs/test-public
          path: public

      - name: Read the release name and create a branch. Push branch to private and public.
        run: |
          RELEASE_NAME=$(gh release view --json name | jq -r '.name')
          RELEASE_BRANCH=release/$RELEASE_NAME
          git branch $RELEASE_BRANCH
          git push -u origin $RELEASE_BRANCH
          git push -u public $RELEASE_BRANCH
        env:
          GITHUB_TOKEN: ${{ secrets.EXTERNAL_REPO_TOKEN }}
